using FinanceManagement.Core.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Core.Entities
{
    public class Transaction
    {
        [Key]
        public Guid TransactionId { get; set; } = Guid.NewGuid();

        public Guid UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; } // Navigation property for the User

        public Guid? CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; } // Navigation property for the Category

        public TransactionTerrority TransactionTerrority { get; set; }

        [Display(Name = "Base Currency Code")]
        public string SelectedCurrency { get; set; } // This will ALWAYS store the USER's base currency code (e.g., "INR")

        [Required]
        public TransactionTimeLine TransactionTimeLine { get; set; }
        public RecurrenceFrequency? RecurrenceFrequency { get; set; }

        [Display(Name = "Amount (In Base Currency)")]
        [Column(TypeName = "decimal(18, 2)")] // Ensure proper SQL type for money
        public decimal? Amount { get; set; } // This will ALWAYS store the amount converted to the user's base currency

        // --- ADDED FIELDS START ---

        [Display(Name = "Original Amount")]
        [Column(TypeName = "decimal(18, 2)")] // Ensure proper SQL type for money
        public decimal? OriginalAmount { get; set; } // Stores the original foreign amount IF TransactionTerritory is International (e.g., 50.00)

        [Display(Name = "Original Currency Code")]
        public string? OriginalCurrency { get; set; } // Stores the original foreign currency code IF TransactionTerritory is International (e.g., "EUR")

        // --- ADDED FIELDS END ---

        public string? Description { get; set; }

        public DateTime? TransactionDate { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }

        // ADDED: Reference to recurring transaction that generated this transaction
        public Guid? GeneratedFromRecurringId { get; set; }

        [ForeignKey(nameof(GeneratedFromRecurringId))]
        public RecurringTransactions? GeneratedFromRecurring { get; set; }

        public bool IsAutoGenerated { get; set; } = false;
    }
}

