using FinanceManagement.Core.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Core.Entities
{
    public class Transaction
    {
        [Key]
        public Guid TransactionId { get; set; } = Guid.NewGuid();

        public Guid UserId { get; set; }
        [ForeignKey("UserId")]
        public User User { get; set; }

        public Guid? CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }

        public TransactionTerrority TransactionTerrority { get; set; }

        [Display(Name = "Base Currency Code")]
        public string SelectedCurrency { get; set; }

        [Required]
        public TransactionTimeLine TransactionTimeLine { get; set; }
        public Frequency? RecurrenceFrequency { get; set; }

        [Display(Name = "Amount (In Base Currency)")]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Amount { get; set; }

        [Display(Name = "Original Amount")]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? OriginalAmount { get; set; }

        [Display(Name = "Original Currency Code")]
        public string? OriginalCurrency { get; set; }

        public string? Description { get; set; }

        public DateTime? TransactionDate { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime? UpdatedAt { get; set; }

        public Guid? GeneratedFromRecurringId { get; set; }

        [ForeignKey(nameof(GeneratedFromRecurringId))]
        public RecurringTransactions? GeneratedFromRecurring { get; set; }

        public bool IsAutoGenerated { get; set; } = false;
    }
}

