using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FinanceManagement.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class doneWithChanges : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RecurringTransactions_Transactions_TransactionId",
                table: "RecurringTransactions");

            migrationBuilder.RenameColumn(
                name: "TransactionId",
                table: "RecurringTransactions",
                newName: "CategoryId");

            migrationBuilder.RenameIndex(
                name: "IX_RecurringTransactions_TransactionId",
                table: "RecurringTransactions",
                newName: "IX_RecurringTransactions_CategoryId");

            migrationBuilder.AddColumn<Guid>(
                name: "GeneratedFromRecurringId",
                table: "Transactions",
                type: "uniqueidentifier",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Transactions",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<decimal>(
                name: "Amount",
                table: "RecurringTransactions",
                type: "decimal(18,2)",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<string>(
                name: "Description",
                table: "RecurringTransactions",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<decimal>(
                name: "OriginalAmount",
                table: "RecurringTransactions",
                type: "decimal(18,2)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "OriginalCurrency",
                table: "RecurringTransactions",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "TransactionCurrency",
                table: "RecurringTransactions",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "TransactionTerrority",
                table: "RecurringTransactions",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateIndex(
                name: "IX_Transactions_GeneratedFromRecurringId",
                table: "Transactions",
                column: "GeneratedFromRecurringId");

            migrationBuilder.AddForeignKey(
                name: "FK_RecurringTransactions_Categories_CategoryId",
                table: "RecurringTransactions",
                column: "CategoryId",
                principalTable: "Categories",
                principalColumn: "CategoryId",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Transactions_RecurringTransactions_GeneratedFromRecurringId",
                table: "Transactions",
                column: "GeneratedFromRecurringId",
                principalTable: "RecurringTransactions",
                principalColumn: "RecurringTransactionId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RecurringTransactions_Categories_CategoryId",
                table: "RecurringTransactions");

            migrationBuilder.DropForeignKey(
                name: "FK_Transactions_RecurringTransactions_GeneratedFromRecurringId",
                table: "Transactions");

            migrationBuilder.DropIndex(
                name: "IX_Transactions_GeneratedFromRecurringId",
                table: "Transactions");

            migrationBuilder.DropColumn(
                name: "GeneratedFromRecurringId",
                table: "Transactions");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Transactions");

            migrationBuilder.DropColumn(
                name: "Amount",
                table: "RecurringTransactions");

            migrationBuilder.DropColumn(
                name: "Description",
                table: "RecurringTransactions");

            migrationBuilder.DropColumn(
                name: "OriginalAmount",
                table: "RecurringTransactions");

            migrationBuilder.DropColumn(
                name: "OriginalCurrency",
                table: "RecurringTransactions");

            migrationBuilder.DropColumn(
                name: "TransactionCurrency",
                table: "RecurringTransactions");

            migrationBuilder.DropColumn(
                name: "TransactionTerrority",
                table: "RecurringTransactions");

            migrationBuilder.RenameColumn(
                name: "CategoryId",
                table: "RecurringTransactions",
                newName: "TransactionId");

            migrationBuilder.RenameIndex(
                name: "IX_RecurringTransactions_CategoryId",
                table: "RecurringTransactions",
                newName: "IX_RecurringTransactions_TransactionId");

            migrationBuilder.AddForeignKey(
                name: "FK_RecurringTransactions_Transactions_TransactionId",
                table: "RecurringTransactions",
                column: "TransactionId",
                principalTable: "Transactions",
                principalColumn: "TransactionId",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
